export const data = [
  {
    id: 1,
    type: 'skills',
    heading1: 'User experience design - UI/UX',
    desc1: 'Delight the user and make it work.',
    heading2: 'web design / development',
    desc2: 'html, css, bootstrap. ',
    heading3: 'react developer',
    desc3: 'html, css, javascript, react ',
  },
  {
    id: 2,
    type: 'Experience',
    heading1: 'frontend development-React ',
    desc1: 'Learning react and getting better',
    heading2: 'web design / development',
    desc2: 'expert in front-end developement',
    heading3: 'graphic design',
    desc3: '6 months experience in adobe illustrator',
  },
  {
    id: 3,
    type: 'education',
    heading1: 'BSc In CSE - Daffodil int university, Dhaka, BD',
    desc1: '2017-2020',
    heading2: 'Hsc - Adamjee cant college, dhaka, BD',
    desc2: '2014-2016',
    heading3: 'ssc - Lalmohan collegiate school, bhola, Barishal',
    desc3: '2014',
  },
]

export const allprojects = [
  {
    id: 1,
    title: 'E - Product Page',
    category: 'react',
    img: './images/product.PNG',
    link: 'https://zaynax-ltd-test.netlify.app/',
  },

  {
    id: 2,
    title: 'Image Card',
    category: 'html & css',
    img: './images/part1.PNG',
    link: 'https://shanto140319.github.io/project-8/',
  },
  {
    id: 3,
    title: 'To do grocery',
    category: 'javascript',
    img: './images/todo.PNG',
    link: 'https://shanto140319.github.io/todo/',
  },
  {
    id: 4,
    title: 'Responsive Grid',
    category: 'html & css',
    img: './images/part2.PNG',
    link: 'https://shanto140319.github.io/project/',
  },
  {
    id: 5,
    title: 'CV Portfolio',
    category: 'html & css',
    img: './images/cv.PNG',
    link: 'https://shanto140319.github.io/CV-02/',
  },
  {
    id: 6,
    title: 'Ecommerce Website',
    category: 'html & css',
    img: './images/drexel.PNG',
    link: 'https://shanto140319.github.io/Drexel-Fulweb-01/index.html',
  },
  {
    id: 7,
    title: 'Unify Business',
    category: 'html & css',
    img: './images/unify.PNG',
    link: 'https://shanto140319.github.io/unify-fullweb-2/index.html',
  },
  {
    id: 8,
    title: 'CountDown Timer',
    category: 'javascript',
    img: './images/count.PNG',
    link: 'https://shanto140319.github.io/countDown/',
  },
  {
    id: 9,
    title: 'Form Validation Pro',
    category: 'javascript',
    img: './images/form.PNG',
    link: 'https://shanto140319.github.io/form-javaScript/',
  },

  {
    id: 10,
    title: 'math quiz',
    category: 'javascript',
    img: './images/math.PNG',
    link: 'https://shanto140319.github.io/mathQuiz/',
  },
  {
    id: 11,
    title: 'Rock Paper Scissors',
    category: 'javascript',
    img: './images/rock.PNG',
    link: 'https://shanto140319.github.io/rock/',
  },
  {
    id: 12,
    title: 'movies db',
    category: 'react',
    img: './images/movie.PNG',
    link: 'https://movie-db-test.netlify.app',
  },

  {
    id: 13,
    title: 'Hacker news',
    category: 'react',
    img: './images/hacker.PNG',
    link: 'https://hacker-news-test.netlify.app/',
  },
  {
    id: 14,
    title: 'sports mania',
    category: 'react',
    img: './images/sports.PNG',
    link: 'https://sport-mania.netlify.app',
  },
  {
    id: 15,
    title: 'submenu',
    category: 'react',
    img: './images/stripe.PNG',
    link: 'https://react-submenu.netlify.app/',
  },
  {
    id: 16,
    title: 'pagination',
    category: 'react',
    img: './images/pagination.PNG',
    link: 'https://react-paginations.netlify.app/',
  },
  {
    id: 17,
    title: 'Covid 19 Live',
    category: 'react',
    img: './images/covid.PNG',
    link: 'https://covid-tracker-live.netlify.app/',
  },
]
